'use client'

import { useState, useCallback } from 'react'
import { generateQrSvg, generateQrDataUrl, validateQrInput } from '../utils'

type QrSize = 200 | 300 | 400

export default function QrGeneratorTool() {
  const [input, setInput] = useState('')
  const [size, setSize] = useState<QrSize>(300)
  const [svgOutput, setSvgOutput] = useState('')
  const [dataUrlOutput, setDataUrlOutput] = useState('')
  const [error, setError] = useState<string | null>(null)
  const [loading, setLoading] = useState(false)
  const [inputError, setInputError] = useState<string | null>(null)

  const handleGenerate = useCallback(async () => {
    const validErr = validateQrInput(input)
    if (validErr) { setInputError(validErr); return }
    setInputError(null)
    setLoading(true)
    setError(null)
    try {
      const [svgResult, dataUrlResult] = await Promise.all([
        generateQrSvg(input, size),
        generateQrDataUrl(input, size),
      ])
      if (svgResult.ok) setSvgOutput(svgResult.svg)
      else setError(svgResult.error)
      if (dataUrlResult.ok) setDataUrlOutput(dataUrlResult.svg)
    } finally {
      setLoading(false)
    }
  }, [input, size])

  const handleDownloadSvg = useCallback(() => {
    if (!svgOutput) return
    const blob = new Blob([svgOutput], { type: 'image/svg+xml' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url; a.download = 'qrcode.svg'; a.click()
    URL.revokeObjectURL(url)
  }, [svgOutput])

  const handleDownloadPng = useCallback(() => {
    if (!dataUrlOutput) return
    const a = document.createElement('a')
    a.href = dataUrlOutput; a.download = 'qrcode.png'; a.click()
  }, [dataUrlOutput])

  const handleKeyDown = useCallback((e: React.KeyboardEvent) => {
    if ((e.ctrlKey || e.metaKey) && e.key === 'Enter') handleGenerate()
  }, [handleGenerate])

  return (
    <div>
      {/* Input area */}
      <div style={{ marginBottom: '1rem' }}>
        <label style={{ display: 'block', fontFamily: 'var(--font-jetbrains), monospace', fontSize: '10px', letterSpacing: '0.1em', color: 'var(--ink-light)', textTransform: 'uppercase', marginBottom: '6px' }}>
          テキスト / URL
        </label>
        <textarea
          value={input}
          onChange={e => { setInput(e.target.value); setInputError(null) }}
          onKeyDown={handleKeyDown}
          placeholder={'https://example.com\nまたは任意のテキスト'}
          rows={4}
          style={{ width: '100%', padding: '1rem', backgroundColor: 'var(--surface-alt)', border: `1px solid ${inputError ? '#b83232' : 'var(--border)'}`, borderRadius: '4px', fontFamily: 'var(--font-noto-sans), sans-serif', fontSize: '14px', color: 'var(--ink)', resize: 'vertical', outline: 'none', lineHeight: 1.65, boxSizing: 'border-box' }}
          onFocus={e => { if (!inputError) e.currentTarget.style.borderColor = 'var(--teal)' }}
          onBlur={e => { e.currentTarget.style.borderColor = inputError ? '#b83232' : 'var(--border)' }}
        />
        {inputError && <div style={{ fontFamily: 'var(--font-noto-sans), sans-serif', fontSize: '12px', color: '#b83232', marginTop: '4px' }}>{inputError}</div>}
      </div>

      {/* Controls */}
      <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.5rem', marginBottom: '1.5rem', alignItems: 'center' }}>
        <div style={{ display: 'flex', gap: '4px' }}>
          {([200, 300, 400] as QrSize[]).map(s => (
            <button key={s} onClick={() => setSize(s)} style={{ fontFamily: 'var(--font-jetbrains), monospace', fontSize: '11px', letterSpacing: '0.05em', padding: '4px 10px', borderRadius: '3px', border: '1px solid var(--border)', cursor: 'pointer', backgroundColor: size === s ? 'var(--navy)' : 'var(--surface)', color: size === s ? '#fff' : 'var(--ink-mid)', transition: 'background 0.15s' }}>
              {s}px
            </button>
          ))}
        </div>
        <button
          onClick={handleGenerate}
          disabled={loading}
          style={{ fontFamily: 'var(--font-jetbrains), monospace', fontSize: '12px', letterSpacing: '0.06em', padding: '6px 20px', borderRadius: '4px', border: 'none', cursor: loading ? 'default' : 'pointer', backgroundColor: 'var(--navy)', color: '#fff', opacity: loading ? 0.7 : 1, transition: 'background 0.15s' }}
        >
          {loading ? '生成中...' : '生成 (Ctrl+Enter)'}
        </button>
      </div>

      {error && (
        <div style={{ fontFamily: 'var(--font-noto-sans), sans-serif', fontSize: '13px', color: '#b83232', backgroundColor: 'rgba(184,50,50,0.06)', border: '1px solid rgba(184,50,50,0.2)', borderRadius: '4px', padding: '0.75rem 1rem', marginBottom: '1rem' }}>
          {error}
        </div>
      )}

      {/* QR Output — SVG is generated by qrcode library, not from user input */}
      {svgOutput && (
        <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '1rem' }}>
          <div
            style={{ border: '1px solid var(--border)', borderRadius: '8px', padding: '16px', backgroundColor: '#faf8f4', display: 'inline-block' }}
            dangerouslySetInnerHTML={{ __html: svgOutput }}
          />
          <div style={{ display: 'flex', gap: '0.5rem' }}>
            <button onClick={handleDownloadSvg} style={{ fontFamily: 'var(--font-jetbrains), monospace', fontSize: '11px', letterSpacing: '0.05em', padding: '6px 16px', borderRadius: '4px', border: 'none', cursor: 'pointer', backgroundColor: 'var(--navy)', color: '#fff', transition: 'background 0.15s' }}>
              SVGダウンロード
            </button>
            <button onClick={handleDownloadPng} style={{ fontFamily: 'var(--font-jetbrains), monospace', fontSize: '11px', letterSpacing: '0.05em', padding: '6px 16px', borderRadius: '4px', border: '1px solid var(--border)', cursor: 'pointer', backgroundColor: 'var(--surface)', color: 'var(--ink-mid)', transition: 'background 0.15s' }}>
              PNGダウンロード
            </button>
          </div>
        </div>
      )}
    </div>
  )
}
