export type Template = {
  id: string
  label: string
  description: string
  content: string
}

export const TEMPLATES: Template[] = [
  {
    id: 'node',
    label: 'Node.js',
    description: 'Node.js / npm プロジェクト',
    content: `# Node.js
node_modules/
npm-debug.log*
yarn-debug.log*
yarn-error.log*
pnpm-debug.log*
.pnpm-store/
package-lock.json
yarn.lock
.npm
.yarn/cache
.yarn/unplugged
.yarn/build-state.yml
.yarn/install-state.gz

# Environment
.env
.env.local
.env.*.local
.env.development
.env.test
.env.production

# Build output
dist/
build/
out/
.next/
.nuxt/
.output/

# OS
.DS_Store
Thumbs.db
desktop.ini`,
  },
  {
    id: 'python',
    label: 'Python',
    description: 'Python / pip プロジェクト',
    content: `# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
share/python-wheels/
*.egg-info/
.installed.cfg
*.egg
MANIFEST

# Virtual environments
.env
.venv
env/
venv/
ENV/
env.bak/
venv.bak/

# Distribution / packaging
.Python

# Unit test / coverage reports
htmlcov/
.tox/
.nox/
.coverage
.coverage.*
.cache
nosetests.xml
coverage.xml
*.cover
*.py,cover
.hypothesis/
.pytest_cache/
cover/

# Jupyter Notebook
.ipynb_checkpoints

# OS
.DS_Store
Thumbs.db`,
  },
  {
    id: 'java',
    label: 'Java',
    description: 'Java / Maven / Gradle',
    content: `# Java
*.class
*.log
*.ctxt
.mtj.tmp/
*.jar
*.war
*.nar
*.ear
*.zip
*.tar.gz
*.rar
hs_err_pid*
replay_pid*

# Maven
target/
pom.xml.tag
pom.xml.releaseBackup
pom.xml.versionsBackup
pom.xml.next
release.properties
dependency-reduced-pom.xml
buildNumber.properties
.mvn/timing.properties
.mvn/wrapper/maven-wrapper.jar

# Gradle
.gradle
**/build/
!src/**/build/
gradle-app.setting
!gradle-wrapper.jar
!gradle-wrapper.properties
.gradletasknamecache

# IDE
.idea/
*.iml
*.iws
*.ipr
out/

# OS
.DS_Store
Thumbs.db`,
  },
  {
    id: 'react',
    label: 'React',
    description: 'React / Create React App / Next.js',
    content: `# Dependencies
node_modules/
.pnp
.pnp.js

# Testing
coverage/

# Next.js
.next/
out/

# Production build
build/
dist/

# Environment variables
.env
.env.local
.env.development.local
.env.test.local
.env.production.local

# Debug logs
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# Runtime
.DS_Store
.env.local
.cache/

# TypeScript
*.tsbuildinfo
next-env.d.ts`,
  },
  {
    id: 'go',
    label: 'Go',
    description: 'Go / Go Modules',
    content: `# Binaries
*.exe
*.exe~
*.dll
*.so
*.dylib
/main

# Test binary
*.test

# Output of go coverage tool
*.out

# Go workspace
go.work

# Vendor directory
vendor/

# Build output
bin/
dist/

# Environment
.env
.env.local

# OS
.DS_Store
Thumbs.db`,
  },
  {
    id: 'rust',
    label: 'Rust',
    description: 'Rust / Cargo',
    content: `# Build output
/target/
Cargo.lock

# Debug
**/*.rs.bk

# Environment
.env
.env.local

# OS
.DS_Store
Thumbs.db`,
  },
  {
    id: 'terraform',
    label: 'Terraform',
    description: 'Terraform / IaC',
    content: `# Local .terraform directories
**/.terraform/*

# .tfstate files
*.tfstate
*.tfstate.*

# Crash log files
crash.log
crash.*.log

# Exclude all .tfvars files (may contain sensitive data)
*.tfvars
*.tfvars.json

# Ignore override files
override.tf
override.tf.json
*_override.tf
*_override.tf.json

# Include override files you wish to add to version control using negation
# !example_override.tf

# .tfplanfile
*.tfplan

# OS
.DS_Store
Thumbs.db`,
  },
  {
    id: 'unity',
    label: 'Unity',
    description: 'Unity ゲームエンジン',
    content: `# Unity generated
[Ll]ibrary/
[Tt]emp/
[Oo]bj/
[Bb]uild/
[Bb]uilds/
[Ll]ogs/
[Uu]ser[Ss]ettings/

# MemoryCaptures
[Mm]emoryCaptures/

# Asset meta data should only be ignored when not using verison control
# (they should be committed when using VCS)
# !/[Aa]ssets/**/*.meta

# Uncomment this line if you wish to ignore the asset store tools plugin
# /[Aa]ssets/AssetStoreTools*

# Autogenerated Jetbrains Rider solution file
[Aa]uto[Gg]enerated/

# Visual Studio cache directory
.vs/

# Gradle cache directory
.gradle/

# Autogenerated VS/MD/Consulo solution and project files
ExportedObj/
.consulo/
*.csproj
*.unityproj
*.sln
*.suo
*.tmp
*.user
*.userprefs
*.pidb
*.booproj
*.svd
*.pdb
*.mdb
*.opendb
*.VC.db

# Unity3D generated meta files
*.pidb.meta
*.pdb.meta
*.mdb.meta

# Unity3D generated file on crash reports
sysinfo.txt

# Builds
*.apk
*.aab
*.unitypackage
*.app

# OS
.DS_Store
Thumbs.db`,
  },
]

const COMMON_ENTRIES = `
# OS generated files
.DS_Store
.DS_Store?
._*
.Spotlight-V100
.Trashes
ehthumbs.db
Thumbs.db
desktop.ini

# Editor files
.vscode/
.idea/
*.swp
*.swo
*~
.project
.classpath
.settings/

# Environment files
.env
.env.local
.env.*.local`.trim()

export function generateGitignore(selectedIds: string[], includeCommon: boolean): string {
  const sections: string[] = []

  selectedIds.forEach(id => {
    const template = TEMPLATES.find(t => t.id === id)
    if (template) {
      sections.push(`# ===== ${template.label} =====\n${template.content}`)
    }
  })

  if (includeCommon) {
    sections.push(`# ===== 共通（OS・エディター）=====\n${COMMON_ENTRIES}`)
  }

  return sections.join('\n\n')
}
